//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.Users = new HashSet<User>();
        }
    
        public int LoginID { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
